name: flutter_manhua
description: manhua

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: '>=0.15.0'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: ^0.12.0

  transparent_image: ^0.1.0

  photo_view: ^0.0.7

  redux: ^3.0.0
  flutter_redux: ^0.5.2

  cached_network_image: ^0.5.1

  flutter_staggered_grid_view: ^0.2.3

  sqflite: ^0.12.2

  mutex: ^1.0.1

  sprintf: ^4.0.0

#  flutter_webview_plugin: ^0.2.1
#  flutter_webview_plugin: path: ./
  flutter_webview_plugin:
    git:
      url: https://github.com/lolizeppelin/flutter_webview_plugin
#      path: tree/webview_post_message
      ref: webview_post_message

  fluwx: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/empty.png
    - assets/pg.png
    - assets/paypal.png
    - assets/book.png

#  fonts:
#    - family: Nunito
#      fonts:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
